### ISSUE TITLE
Upgrading from 1.5 to 1.6

### ISSUE THREAD

**Issue by gflcampos** [obiba/docker-opal-rserver#2]
Hi!

When using this image, presumably, you will want to persist the `/srv` directory between executions by using a volume.
If you have v1.5, you will have [this](https://github.com/obiba/docker-opal-rserver/blob/f1bedc23d9903eb67b0a80e297f52bcc7f1e6be2/1.5/conf/Rserv.conf) version of Rserv.conf in your `/srv/conf` dir.  
This file loads file `/var/lib/rserver/conf/Rprofile.R`.

The problem is that, when you upgrade to 1.6, `/var/lib/rserver` does not exist, because the new Dockerfile now uses `/usr/share/rserver` instead. And the new `Rserv.conf` and `Rprofile.R` files will not be copied to `/srv/conf` because the if condition in [start.sh](https://github.com/obiba/docker-opal-rserver/blob/master/bin/start.sh) fails.

So Rserver will still try to load `/var/lib/rserver/conf/Rprofile.R` and fail. This means that the `HOME` env var is never set. I think this is what is causing the following error when starting the rserver container:

```
> library(Rserve) ; Rserve(args='--vanilla --RS-workdir /srv/work/R --RS-conf /srv/conf/Rserv.conf')
Starting Rserve:
 /usr/lib/R/bin/R CMD /usr/local/lib/R/site-library/Rserve/libs//Rserve --vanilla --RS-workdir /srv/work/R --RS-conf /srv/conf/Rserv.conf 


R version 4.0.1 (2020-06-06) -- "See Things Now"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/var/lib/rserver/conf/Rprofile.R': No such file or directory
Rserv started in daemon mode.
> 
> 
Loading required package: resourcer
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages("resourcer", repos = c("https://cloud.r-project.org",  :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) Error in install.packages("resourcer", repos = c("https://cloud.r-project.org",  : 
  unable to install packages
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘resourcer’
```

As a workaround, I moved the `cp` command to outside of the if statement so that `Rserv.conf` and `Rprofile.R` are always copied to `/srv/conf`.

**Comment by ymarcon** [comment]
Thanks for the report. Please try again with the `snapshot` tag. Let me know how it goes and if ok I will build  `1.6` and `latest` tags as well.

**Comment by ymarcon** [comment]
I have rebuilt 1.6 and latest images.
